### ISSUE TITLE
Facebook module

### ISSUE THREAD

**Issue by ozsteyr** [ex0dus-0x/brut3k1t#12]
Tried on my own fb id with custom wordlist with multiple entries of correct password and no luck.
Is there options im missing?

**Comment by ssysm** [comment]
Using Firefox or chrome ?

**Comment by ssysm** [comment]
Using Firefox or chrome ?

**Comment by ozsteyr** [comment]
Both..?

**Comment by ssysm** [comment]
This tool require Firefox to run the program. Change your default browser to Firefox and try it again. If you do everything correctly, a Firefox windows will pop-up to run the program.

**Comment by ozsteyr** [comment]
I clearly have no idea. I thought this was used via cli. Could you please give me a quick over view of its use please?

**Comment by ssysm** [comment]
Try uninstall chrome and set Firefox as default browser. Then run program in CLI. If everything set correctly, program will make a pop-up window in Firefox then the program will start. Facebook module is still under construction. This module is a web-based so it need Firefox to run.

**Comment by ex0dus-0x** [comment]
It is not dependent on whether you have Firefox installed or not.

The facebook module is under active development. I've received a lot of requests about it, and I'm exploring possible solutions with web scraping and such.

**Comment by ex0dus-0x** [comment]
Fixed! Facebook module should work now. Try again! Please make sure that you have all the necessary dependencies from the `installer.py` file.

**Comment by ozsteyr** [comment]
^[      Invalid debugflag given: always
Invalid debugflag given: nodebuilder
DEBUG:
DEBUG: Debug created for /usr/local/lib/python2.7/dist-packages/xmpp/client.py
DEBUG:  flags defined:

This appears after each attempt. 
Updated with installer and all dependencies.
Still no luck though.

**Comment by ex0dus-0x** [comment]
Are you attempting to bruteforce XMPP? This is very particular and not a problem I've seen. Please provide what you input as well.

**Comment by ozsteyr** [comment]
No worries,
python brut3k1t.py -s facebook -u "MY FB ID" -w "MY WORDLIST".txt
Just trying my FB login. Is there a way of being more direct  in how to try FB?, like maybe mobile login or sonething?

**Comment by ex0dus-0x** [comment]
I've fixed the repository so that you can utilize an actual username. To update your repo:

    git pull

or reclone. Then run `installer.py` and try again.

**Comment by ozsteyr** [comment]
Re-cloned, installed.

[*] Username: RobertLaw
[*] Wordlist: /root/pw1.txt
[*] Service: facebook
[*] Checking if username exists...
Traceback (most recent call last):
  File "brut3k1t.py", line 193, in <module>
    main()
  File "brut3k1t.py", line 172, in main
    if facebookCheck(username) == 1:
  File "src/facebookLib.py", line 19, in facebookCheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 140, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.firefox.service.Service object at 0xf3c82cd0>> ignored

**Comment by ex0dus-0x** [comment]
What is your operating system? It seems as if you are using OS X. In this case, try TO uninstall selenium, and then downgrading it:

    pip install selenium==2.53.6

Also, make sure you have Firefox. I will try to make some updates because of problems users are running into with the `firefoxdriver`

**Comment by ozsteyr** [comment]
Uninstalled and downgraded selenium. I run latest kali on pc.


[*] Checking if username exists...
Traceback (most recent call last):
  File "brut3k1t.py", line 193, in <module>
    main()
  File "brut3k1t.py", line 172, in main
    if facebookCheck(username) == 1:
  File "src/facebookLib.py", line 19, in facebookCheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 99, in _wait_until_connectable
    "The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

**Comment by ex0dus-0x** [comment]
If you can, install Teamviewer on your Kali Linux build. I want to see the problem myself and attempt to diagnose it.

**Comment by ex0dus-0x** [comment]
Problem fixed. Do 

    git pull

or reclone. Closing due to inactivity

**Comment by ozsteyr** [comment]
Apologies, ive been on christmas holidays. And a big thankyou.

**Comment by ozsteyr** [comment]
You BEAUTY!!
